### ISSUE TITLE
Passwall+Smartdns，开启访问控制会导致bug

### ISSUE THREAD

**Issue by BlueDolphin9527** [luckyyyyy/blog#66]
Dns的设置如图，![image](https://user-images.githubusercontent.com/62049321/179169568-6c6e915b-3f06-49ba-aac1-bb4b226eac9a.png)
经过多次测试，发现passwall+Smartdns，在不开启访问控制的时候，可以正常使用。
![image](https://user-images.githubusercontent.com/62049321/179169813-55c2f2ff-2490-4bc6-a1d6-b8f60d5631c0.png)
![image](https://user-images.githubusercontent.com/62049321/179169851-cd8d0b88-5c6a-41ae-b721-2da29700f844.png)
(PS：此时延迟高，是因为我开启了路由器全局代理。)

而一但开启访问控制，就会导致dns失效，打不开任何的域名，首页的百度测试和github测试都无法连接，界面上的dns显示未运行。
![image](https://user-images.githubusercontent.com/62049321/179169458-fb58b40f-7258-493f-84b0-117f09f9ba79.png)
![image](https://user-images.githubusercontent.com/62049321/179169407-d4edb693-6790-413c-a2cb-fe7fe95e548f.png)
![image](https://user-images.githubusercontent.com/62049321/179170836-fb717d62-1903-4410-a20d-04c34773eb87.png)

请求能修复一下这个bug，因为访问控制我非常需要。

**Comment by BlueDolphin9527** [comment]
> 应该是有问题，单未必是访问控制层面，我这边访问控制有列表，smartdns分流时好时坏，能复现的是，在编辑smartdns配置后应用会发生新访问域名全部解析失败，但是passwall修改dns分流方式或更新规则后应用则能正常使用

那建议尽快解决这个bug吧，挺烦人的。

**Comment by yanghonghao6789** [comment]
smartdns开启了
pw的dns选择dnsmasq 访问控制不开启的情况下  分流如下  网络正常
![image](https://user-images.githubusercontent.com/73630536/208032950-4bf5a456-461c-40a2-b77b-4a06b49e322f.png)

![image](https://user-images.githubusercontent.com/73630536/208033214-9dee72bf-85e1-48fc-a197-bc8c9a7cd5eb.png)
开启访问控制之后  国内没网  代理有网  开的是docker里青龙容器 设置全局   非常纳闷 为啥国内没网  代理有网

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/208033451-3adf3044-6869-4ec9-abfb-548da4487bbd.png)

![image](https://user-images.githubusercontent.com/73630536/208033644-daef20a4-6c41-4815-bed1-8fa086215ed3.png)

![image](https://user-images.githubusercontent.com/73630536/208033691-0a2b9e63-88af-40ca-9539-e4b1ac61688f.png)

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/208034349-21bbd576-db95-405d-8f4e-c78d689b5465.png)

访问控制是起作用了 青龙被全局代理  但是 国内没有网络怎么办

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/208034513-ae22859d-018b-4060-8f8c-d07c786e9648.png)

不用分流也是这样的错误
